### ISSUE TITLE
Creating a Network Insight configuration file for Cisco SG300-20

### ISSUE THREAD

**Issue by vmwarelab** [vmware/network-insight-sdk-generic-datasources#37]
Following the steps resulted in this error 

File "./network_insight_sdk_generic_datasources/main.py", line 6, in <module>
    import network_insight_sdk_generic_datasources.common.yaml_utilities as yaml_utilities
ImportError: No module named network_insight_sdk_generic_datasources.common.yaml_utilities

**Comment by smitmartijn** [comment]
Hi @vmwarelab - This looks like the project folder is not in your PYTHONPATH, as mentioned in step 3. Make sure you do something like this: export PYTHONPATH=~/network-insight-sdk-generic-datasources  - assuming you cloned the repository in your home folder, otherwise provide the appropriate path.

**Comment by vmwarelab** [comment]
that worked compare to the example on the main page.
export PYTHONPATH="$PYTHONPATH:../network-insight-sdk-generic-datasources"

now i have another error..

File "./network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "./network_insight_sdk_generic_datasources/main.py", line 44, in main
    args.model] else None
KeyError: 'sg300


I m trying to add a cisco sg300-20 as a data source in Network Insight  and here is the command i m using 

 python ./network_insight_sdk_generic_datasources/main.py -d cisco -m sg300 -s CISCO_IOS -i 192.168.110.1 -u my_username-p my_password -o cisco-sg300-192.168.110.1.zip

**Comment by smitmartijn** [comment]
How does the sg300.yml file look? As that's not an available template in this repo, I'm assuming you're building it. 

If you're not building it, be aware that this SDK does only support the templates that it is given. More on how to build one, here: https://github.com/vmware/network-insight-sdk-generic-datasources/blob/master/EXAMPLE.md

**Comment by vmwarelab** [comment]
so now i have to build my own yml.. :). dont know really how to do that. so basically i cant just add a generic switch / router if its not mentioned on the page or have a yaml in the repo for the sdk.

Great!

**Comment by smitmartijn** [comment]
Yes, as the SDK needs to know what commands to execute on the switch and it needs to be able to understand the output. All switches have some things different in the way they handle the info that vRNI needs.

If you're up for it, the EXAMPLE.md file lists how to get started with it. I'll close this issue for now.
