### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by vmwarelab** [vmware/network-insight-sdk-generic-datasources#50]
in my home lab i have a cisco RV-340 Router and two SG-300-20 small business managed switches.
would i be able to use the SDK to add them as endpoint . i m wondering if anyone tried and got it to work

**Comment by piyushvmware** [comment]
Yes, that would be possible. Typical SDK deployment would be
1. Deploy a separate VM for SDK. Lets call it SDM-VM.
2. SDK-VM should be able to connect to devices and retrieve data.
3. SDK-VM should be able to talk to vRNI platform VM to upload config data.
4. If step 3 does not work then upload generated zip file to vRNI.
You are also set to view info on vRNI.

**Comment by vmwarelab** [comment]
is there a particular linux distro for the steps mentioned in the example

**Comment by piyushvmware** [comment]
You can use ubuntu or any other open source linux. There is no hard requirement of OS selection. But you might want to consider python3/pip3 command instead of python/pip. Unless you have command aliases.

**Comment by vmwarelab** [comment]
i m using ubuntu 16.04 and i getting the following error 

Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 6, in <module>
    import network_insight_sdk_generic_datasources.common.yaml_utilities as yaml_utilities
ImportError: No module named network_insight_sdk_generic_datasources.common.yaml_utilities

**Comment by piyushvmware** [comment]
What is the PYTHONPATH in your case ? You shouldn't set it using export command. Main snippet to get SDK running is shown below. (To be executed in sequence)

$ git clone https://github.com/vmware/network-insight-sdk-generic-datasources.git
$ cd network-insight-sdk-generic-datasources
$ pip install --src . -r requirements.txt
$ export PYTHONPATH="$PYTHONPATH:../network-insight-sdk-generic-datasources"
$ python ./network_insight_sdk_generic_datasources/main.py -d cisco -m n5k -s CISCO_IOS -i 10.1.1.1

**Comment by vmwarelab** [comment]
that what i followed yes

**Comment by piyushvmware** [comment]
Yes you are right. It was typo.
`python ./network_insight_sdk_generic_datasources/main.py -d cisco -m n5k -s CISCO_IOS -i 10.1.1.1 -u test -p test -o cisco-n5k-10.1.1.1.zip`
Can you paste PYTHONPATH ?

**Comment by vmwarelab** [comment]
thats what i used. you python command is missing the switch ip and creds . i thought the script needed to access the switch to generate the zip file 

here what my command look 

python ./network_insight_sdk_generic_datasources/main.py -d cisco -m sg-300 -s CISCO_IOS -i 192.168.0.2 -u myusername -p Mypassword -o cisco-sg300-192.168.0.2.zip

**Comment by vmwarelab** [comment]
root@vra-vmwlab-frontend-316:~/vrni/network-insight-sdk-generic-datasources# echo $PYTHONPATH
:../network-insight-sdk-generic-datasources:../network-insight-sdk-generic-datasources

**Comment by vmwarelab** [comment]
I unset and set the export now i am getting this 


Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 6, in <module>
    import network_insight_sdk_generic_datasources.common.yaml_utilities as yaml_utilities
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/common/yaml_utilities.py", line 5, in <module>
    import yaml
ImportError: No module named yaml

**Comment by piyushvmware** [comment]
Try following.
1. Fix PYTHONPATH
export PYTHONPATH=":../network-insight-sdk-generic-datasources"
2. Use pip3 to install deps
pip3 install --src . -r requirements.txt
3. Try running python3

**Comment by piyushvmware** [comment]
Please run above commands from network-insight-sdk-generic-datasources base directory.

**Comment by vmwarelab** [comment]
error when using python3 command 

Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "./network_insight_sdk_generic_datasources/main.py", line 32, in main
    import network_insight_sdk_generic_datasources.common.physical_device as physical_device
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/common/physical_device.py", line 7, in <module>
    from network_insight_sdk_generic_datasources.connection.ssh_connect_handler import SSHConnectHandler
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/connection/ssh_connect_handler.py", line 4, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

**Comment by vmwarelab** [comment]
i did verify and was able to ssh into the switch from the host where i have the sdk installed

**Comment by piyushvmware** [comment]
python3 is what we should use.

Just checking if deps are present. Please run following.
`pip3 install netmiko requests pyyaml netaddr` 
Above it fix deps issue.

Then run SDK with python3.

**Comment by vmwarelab** [comment]
root@vra-vmwlab-frontend-316:~/vrni/network-insight-sdk-generic-datasources# pip3 install netmiko requests pyyaml netaddr
Requirement already satisfied (use --upgrade to upgrade): netmiko in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): textfsm in /usr/local/lib/python3.5/dist-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): pyserial in /usr/lib/python3/dist-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): scp>=0.13.2 in /usr/local/lib/python3.5/dist-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): paramiko>=2.4.3 in /usr/local/lib/python3.5/dist-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=38.4.0 in /usr/local/lib/python3.5/dist-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): importlib-resources; python_version < "3.7" in /usr/local/lib/python3.5/dist-packages (from netaddr)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from textfsm->netmiko)
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python3.5/dist-packages (from textfsm->netmiko)
Requirement already satisfied (use --upgrade to upgrade): bcrypt>=3.1.3 in /usr/local/lib/python3.5/dist-packages (from paramiko>=2.4.3->netmiko)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=2.5 in /usr/local/lib/python3.5/dist-packages (from paramiko>=2.4.3->netmiko)
Requirement already satisfied (use --upgrade to upgrade): pynacl>=1.0.1 in /usr/local/lib/python3.5/dist-packages (from paramiko>=2.4.3->netmiko)
Requirement already satisfied (use --upgrade to upgrade): zipp>=0.4; python_version < "3.8" in /usr/local/lib/python3.5/dist-packages (from importlib-resources; python_version < "3.7"->netaddr)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1 in /usr/local/lib/python3.5/dist-packages (from bcrypt>=3.1.3->paramiko>=2.4.3->netmiko)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.3->netmiko)
You are using pip version 8.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by vmwarelab** [comment]
it seems all the requirements already satisfied

**Comment by vmwarelab** [comment]
still getting the same error 


Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "./network_insight_sdk_generic_datasources/main.py", line 32, in main
    import network_insight_sdk_generic_datasources.common.physical_device as physical_device
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/common/physical_device.py", line 7, in <module>
    from network_insight_sdk_generic_datasources.connection.ssh_connect_handler import SSHConnectHandler
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/connection/ssh_connect_handler.py", line 4, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"

**Comment by piyushvmware** [comment]
netmiko is problem here. Older versions don't work with python3.

Can you once try following ? 
`pip3 install --upgrade netmiko requests pyyaml netaddr`
Is it also possible to upgrade `pip install --upgrade pip`

**Comment by vmwarelab** [comment]
i tried pip install --upgrade pip before . its says command doesnt exist.. i am using pip3

**Comment by piyushvmware** [comment]
Which OS are you using ? We need to make sure python3 and pip3 are install properly. OS specific commands are required to configure python properly. Although, running SDK is not OS specific but python installation & configuration is dependant on OS.

**Comment by vmwarelab** [comment]
ubuntu 16.04 . idid install python3 and pip3  but its still says when i try to upgrade pip

root@vra-vmwlab-frontend-316:~/vrni/network-insight-sdk-generic-datasources# pip install --upgrade pip
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by vmwarelab** [comment]
do i need to uninstall python 2.7

**Comment by vmwarelab** [comment]
i cant seem to unistall Python 2.7.12  as i have purged it many times

root@vra-vmwlab-frontend-316:~/vrni/network-insight-sdk-generic-datasources# python -V
Python 2.7.12

**Comment by piyushvmware** [comment]
No. Ubuntu needs 2.7.
Let me come on this.

**Comment by vmwarelab** [comment]
okay i have no idea. 

if i run this right now 
pip3 install --upgrade netmiko requests pyyaml netaddr

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-meajfv2z/pynacl/
You are using pip version 8.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by vmwarelab** [comment]
and when i try to upgrade pip now i get 


root@vra-vmwlab-frontend-316:~/vrni/network-insight-sdk-generic-datasources# pip install --upgrade pip
-su: /usr/bin/pip: No such file or directory

**Comment by vmwarelab** [comment]
i reinstalled pip 
**apt install python-pip**

then i ran 

root@vra-vmwlab-frontend-316:~/vrni/network-insight-sdk-generic-datasources# **pip install --src . -r requirements.txt**
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: netmiko in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2.24.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: netaddr in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.8.0)
Obtaining network-insight-sdk-python from git+https://github.com/vmware/network-insight-sdk-python.git#egg=network-insight-sdk-python (from -r requirements.txt (line 5))
  Updating ./network-insight-sdk-python clone
  Running command git fetch -q --tags
  Running command git reset --hard -q f85eb7df919500fc2cee5611558a1ba407247cdf
Requirement already satisfied: setuptools>=38.4.0 in /usr/local/lib/python2.7/dist-packages (from netmiko->-r requirements.txt (line 1)) (44.1.1)
Requirement already satisfied: scp>=0.13.2 in /usr/local/lib/python2.7/dist-packages (from netmiko->-r requirements.txt (line 1)) (0.13.2)
Requirement already satisfied: pyserial in /usr/local/lib/python2.7/dist-packages (from netmiko->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: paramiko>=2.4.3 in /usr/local/lib/python2.7/dist-packages (from netmiko->-r requirements.txt (line 1)) (2.7.1)
Requirement already satisfied: textfsm in /usr/local/lib/python2.7/dist-packages (from netmiko->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 2)) (1.25.10)
Requirement already satisfied: importlib-resources; python_version < "3.7" in /usr/local/lib/python2.7/dist-packages (from netaddr->-r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (3.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (3.1.7)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from textfsm->netmiko->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from textfsm->netmiko->-r requirements.txt (line 1)) (0.18.2)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from importlib-resources; python_version < "3.7"->netaddr->-r requirements.txt (line 4)) (1.2.0)
Requirement already satisfied: singledispatch; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from importlib-resources; python_version < "3.7"->netaddr->-r requirements.txt (line 4)) (3.4.0.3)
Requirement already satisfied: pathlib2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-resources; python_version < "3.7"->netaddr->-r requirements.txt (line 4)) (2.3.5)
Requirement already satisfied: contextlib2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-resources; python_version < "3.7"->netaddr->-r requirements.txt (line 4)) (0.6.0.post1)
Requirement already satisfied: typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from importlib-resources; python_version < "3.7"->netaddr->-r requirements.txt (line 4)) (3.7.4.3)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.5->paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (1.0.23)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.5->paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.5->paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (1.1.10)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version < "3"->importlib-resources; python_version < "3.7"->netaddr->-r requirements.txt (line 4)) (1.10.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.5->paramiko>=2.4.3->netmiko->-r requirements.txt (line 1)) (2.20)
Installing collected packages: network-insight-sdk-python
  Attempting uninstall: network-insight-sdk-python
    Found existing installation: network-insight-sdk-python 0.0.1.dev126
    Uninstalling network-insight-sdk-python-0.0.1.dev126:
      Successfully uninstalled network-insight-sdk-python-0.0.1.dev126
  Running setup.py develop for network-insight-sdk-python
Successfully installed network-insight-sdk-python


then when executing the sdk i m getting that netmiko model isnt there lol ..   which was instlled as part of the requirement file


Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "./network_insight_sdk_generic_datasources/main.py", line 32, in main
    import network_insight_sdk_generic_datasources.common.physical_device as physical_device
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/common/physical_device.py", line 7, in <module>
    from network_insight_sdk_generic_datasources.connection.ssh_connect_handler import SSHConnectHandler
  File "/root/vrni/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/connection/ssh_connect_handler.py", line 4, in <module>
    from netmiko import ConnectHandler
ModuleNotFoundError: No module named 'netmiko'

**Comment by vmwarelab** [comment]
if you have it working on some linux distro .. i can deploy that distro .. with buntu 16 it seems like a chicken and egg problem

**Comment by piyushvmware** [comment]
You need to fix python/python3/python-pip/python3-pip installations. Once that is done we can try running SDK. 
It gets really hard if you try to uninstall python2 from ubuntu which is not at all recommended. Linux distros depend on python. 

You can try with latest ubuntu 20.04. I would recommend to not uninstall anything. Both python 2.7 and 3.x can coexist. It is just the commands that you use. Here, it would be pip3 and python3.

**Comment by vmwarelab** [comment]
i was using only pip3 and python 3 ... you asked me if i may as well upgrade pip which it seems i cant at the moment
let me deploy unbuntu 20 and try the sdk then

**Comment by vmwarelab** [comment]
No dice.    have setup a new Ubuntu 20  and installed pip3 and python3
getting now this error 

Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 6, in <module>
    import network_insight_sdk_generic_datasources.common.yaml_utilities as yaml_utilities
ModuleNotFoundError: No module named 'network_insight_sdk_generic_datasources'

**Comment by smitmartijn** [comment]
That last error happens when PYTHONPATH isn't set. Please let us know if you've solved it already.

**Comment by smitmartijn** [comment]
Closing.
