### ISSUE TITLE
No such file - huawei.yml

### ISSUE THREAD

**Issue by notrhythm** [vmware/network-insight-sdk-generic-datasources#55]
### Describe the bug

Hello, dear friends.

After running the command: 
python3.8 ./network_insight_sdk_generic_datasources/main.py -d huawei -m S6330 -s HUAWEI -i 10.1.1.1 -u i.username -p mypasswd -o outconf.zip

I faced with next error:
FileNotFoundError: [Errno 2] No such file or directory: './network_insight_sdk_generic_datasources/routers_and_switches/huawei/huawei.yml'

![image](https://user-images.githubusercontent.com/65127887/178925054-b0d581ee-c40e-499c-a1c1-d356109938b3.png)

![image](https://user-images.githubusercontent.com/65127887/178927865-8ae48fdc-8793-49d6-9823-c3185448bca5.png)

Maybe you know how to fix it?

Thank you in advance!

### Reproduction steps

```bash
run the command:
python3.8 ./network_insight_sdk_generic_datasources/main.py -d huawei -m S6330 -s HUAWEI -i 10.1.1.1 -u i.username -p mypasswd -o outconf.zip
```

### Expected behavior

Creation outconf.zip for uploading to vRNI

**Comment by piyushvm** [comment]
Hello @notrhythm,

Huawei is not supported by this SDK as Huawei is supported by vRNI. You could directly add Huawei to vRNI and check if all the entities are getting created.

Thanks,
Piyush
